// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'topic': string;
  'topic__sub_topic': string;
  'topic__sub_topic__title': string;
  'topic__text': string;
  'topic__title': string;
}
export const cssExports: CssExports;
export default cssExports;
