// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__nav_links': string;
  'header__settings': string;
}
export const cssExports: CssExports;
export default cssExports;
