// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'job': string;
  'job__cards': string;
  'job__header': string;
}
export const cssExports: CssExports;
export default cssExports;
