// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'banner__container': string;
  'banner__container__button_group': string;
  'banner__container__description': string;
  'banner__container__header': string;
}
export const cssExports: CssExports;
export default cssExports;
