// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'header_nav_link': string;
  'header_nav_link__active': string;
}
export const cssExports: CssExports;
export default cssExports;
