// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info_block': string;
  'info_block__descritption': string;
  'info_block__header': string;
}
export const cssExports: CssExports;
export default cssExports;
