// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'projects': string;
  'projects__navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
