// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'product_navigation_block': string;
  'product_navigation_block__subtopics': string;
  'product_navigation_block__topic': string;
  'product_navigation_block__topic__ellipse': string;
}
export const cssExports: CssExports;
export default cssExports;
