// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer_info_block': string;
  'footer_info_block__header': string;
}
export const cssExports: CssExports;
export default cssExports;
