// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navigation_block': string;
  'navigation_block__genre': string;
  'navigation_block__nav_links': string;
}
export const cssExports: CssExports;
export default cssExports;
