// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'job_card': string;
  'job_card__description': string;
  'job_card__header': string;
  'job_card__links': string;
}
export const cssExports: CssExports;
export default cssExports;
